#!/bin/bash

############################################
### Check main installation requirements ###
############################################

set -e

BINARY="/usr/bin/dotnet"

# Binary
echo "Checking binary is present and its usefulness"
test -e "${BINARY}"
dotnet --version
dotnet --info