#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*

# Run PR validation on all branches
pr:
  autoCancel: true
  branches:
    include:
    - '*'

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: _TeamName
  value:  AspNetCore

jobs:
- template: jobs/default-build.yml
  parameters:
    condition: ne(variables['SkipTests'], 'true')
    jobName: Components_E2E_Test
    jobDisplayName: "Test: Blazor E2E tests on Linux"
    agentOs: Linux
    installNodeJs: true
    installJdk: true
    isTestingJob: true
    steps:
    - script: git submodule update --init
      displayName: Update submodules
    - script: ./restore.sh
      displayName: Run restore.sh
    - script: npm install --prefix ./src/Components/test/E2ETest
      displayName: NPM install
    - script: .dotnet/dotnet build ./src/Components/test/E2ETest -c $(BuildConfiguration) --no-restore
      displayName: Build
    - script: .dotnet/dotnet test ./src/Components/test/E2ETest -c $(BuildConfiguration) --no-build --filter 'Quarantined!=true|Quarantined=false'
                 --logger:"trx%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.trx"
                 --logger:"html%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.html"
                 --results-directory $(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Unquarantined
      displayName: Run E2E tests
    - script: .dotnet/dotnet test ./src/Components/test/E2ETest -c $(BuildConfiguration) --no-build --filter 'Quarantined=true' -p:RunQuarantinedTests=true
                 --logger:"trx%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.trx"
                 --logger:"html%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.html"
                 --results-directory $(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Quarantined
      displayName: Run Quarantined E2E tests
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish E2E Test Results
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Unquarantined'
        testRunTitle: ComponentsE2E-$(AgentOsName)-$(BuildConfiguration)-xunit
      condition: always()
    - task: PublishTestResults@2
      displayName: Publish Quarantined E2E Test Results
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Quarantined'
        testRunTitle: Quarantine-$(AgentOsName)-$(BuildConfiguration)-xunit
        mergeTestResults: true
      condition: always()

    artifacts:
    - name: Components_E2E_Test_Logs
      path: '$(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)'
      publishOnError: true
