trigger:
- main
- exp/*
- vs*

jobs:
- job: BootstrapMSBuildOnFullFrameworkWindows
  displayName: "Windows Full"
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: BatchScript@1
    displayName: cibuild_bootstrapped_msbuild.cmd
    inputs:
      filename: 'eng/cibuild_bootstrapped_msbuild.cmd'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-full Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Debug/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Windows-on-full .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'FullOnWindows build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'FullOnWindows test logs'
    continueOnError: true
    condition: always()

- job: BootstrapMSBuildOnCoreWindows
  displayName: "Windows Core"
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: BatchScript@1
    displayName: cibuild_bootstrapped_msbuild.cmd
    inputs:
      filename: 'eng/cibuild_bootstrapped_msbuild.cmd'
      arguments: '-msbuildEngine dotnet'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-Core Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Debug/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Windows-on-Core .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'CoreOnWindows build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'CoreOnWindows test logs'
    continueOnError: true
    condition: always()

- job: FullReleaseOnWindows
  displayName: "Windows Full Release (no bootstrap)"
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: BatchScript@1
    displayName: cibuild.cmd
    inputs:
      filename: 'eng/cibuild.cmd'
      arguments: '-configuration Release -test'
  - task: PublishTestResults@2
    displayName: Publish .NET Framework Test Results
    inputs:
      testRunTitle: 'Windows-on-full Release Full Framework'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Release/*UnitTests_net472*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Windows-on-full Release .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/Log/Release'
      ArtifactName: 'FullOnWindows Release build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'FullOnWindows Release test logs'
    continueOnError: true
    condition: always()

- job: RichCodeNavIndex
  displayName: "Windows Code Indexing"
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: BatchScript@1
    displayName: build.cmd
    inputs:
      filename: 'build.cmd'
  - task: RichCodeNavIndexer@0
    displayName: RichCodeNav Upload
    inputs:
      languages: 'csharp'
    continueOnError: true
    condition: succeeded()

- job: CoreBootstrappedOnLinux
  displayName: "Linux Core"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: . 'eng/cibuild_bootstrapped_msbuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'Linux .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'CoreOnLinux build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'CoreOnLinux test logs'
    continueOnError: true
    condition: always()

- job: CoreOnMac
  displayName: "macOS Core"
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - bash: . 'eng/cibuild_bootstrapped_msbuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish .NET Test Results
    inputs:
      testRunTitle: 'macOS .NET'
      testRunner: XUnit
      testResultsFiles: |
        artifacts/TestResults/**/*.xml
        !**/*UnitTests_net472*.xml
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log/Debug'
      ArtifactName: 'CoreOnMac build logs'
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'CoreOnMac test logs'
    continueOnError: true
    condition: always()

- job: MonoOnMac
  # Mono CI disabled until it can parse C# 9 syntax: https://github.com/dotnet/msbuild/issues/6058
  condition: eq(1,2)
  displayName: "macOS Mono"
  pool:
    vmImage: 'macOS-10.14'
  steps:
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#mono
  - bash: |
      SYMLINK=6_4_2
      MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
      echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
      echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
      echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
    displayName: Use Mono 6.4.2
  - bash: 'eng/cibuild_bootstrapped_msbuild.sh --host_type mono /p:SuppressLicenseValidation=true'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish Mono Test Results
    inputs:
      testRunTitle: 'macOS Mono'
      testRunner: XUnit
      testResultsFiles: 'artifacts/TestResults/Debug-MONO/*UnitTests*.xml'
      publishRunAttachments: true
      mergeTestResults: true
    continueOnError: true
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: logs'
    inputs:
      PathtoPublish: 'artifacts/log'
      ArtifactName: 'MonoOnMac build logs'
    condition: always()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: TestResults'
    inputs:
      PathtoPublish: 'artifacts/TestResults'
      ArtifactName: 'MonoOnMac test logs'
    continueOnError: true
    condition: always()

- template: /eng/common/templates/job/source-build.yml
  parameters:
    platform:
      name: 'Managed'
      container: 'mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343'
